### PR TITLE
updating version of alpine and node - fixing errors in paths and bina…

### PR DESCRIPTION
**Pull request by marlluslustosa**
updating version of alpine and node - fixing errors in paths and binaries

### CODE REVIEW

**Comment by marlluslustosa** [comment]
:P

**Comment by Ezka77** [comment]
Still not sure about switching to the official node but it does not make a huge size difference in the end ; and from where the `url-loader` is required ? (and why was it not needed previously ?)

**Comment by marlluslustosa** [comment]
The recommendation when working with Docker to generate images with Dockerfile is to always prefer to start a previous image (FROM) from official repositories (when these exist). This is the case with the node. You are using a third-party image, while you have the availability to use the node-alpine image itself (much more updated and maintained by the community and more certain that it can continue to be maintained). So my suggestion.

**Comment by Ezka77** [comment]
You right. I've use mhart images as they were really small and he provided the old version used by XOA. Now it's not so useful.

Thanks !

**Pull request merged**
